package com.pitzzahh.entity;

public enum SearchingType {

    SEARCH_BY_STUDENT_NUMBER,                       // 1
    SEARCH_BY_STUDENT_NAME,                         // 2
    SEARCH_BY_STUDENT_AGE,                          // 3
    SEARCH_BY_STUDENT_ADDRESS,                      // 4
    SEARCH_BY_STUDENT_COURSE,                       // 5
    SEARCH_BY_STUDENT_NUMBER_AND_STUDENT_NAME,      // 6
    SEARCH_BY_STUDENT_NUMBER_AND_STUDENT_AGE,       // 7
    SEARCH_BY_STUDENT_NUMBER_AND_STUDENT_ADDRESS,   // 8
    SEARCH_BY_STUDENT_NUMBER_AND_STUDENT_COURSE,    // 9
    SEARCH_BY_STUDENT_NAME_AND_STUDENT_AGE,         // 10
    SEARCH_BY_STUDENT_NAME_AND_STUDENT_ADDRESS,     // 11
    SEARCH_BY_STUDENT_NAME_AND_STUDENT_COURSE,      // 12
    SEARCH_BY_STUDENT_AGE_AND_STUDENT_ADDRESS,      // 13
    SEARCH_BY_STUDENT_AGE_AND_STUDENT_COURSE,       // 14
    SEARCH_BY_STUDENT_ADDRESS_AND_STUDENT_AGE,      // 15
    SEARCH_BY_STUDENT_ADDRESS_AND_STUDENT_COURSE,   // 16

}
